name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
#assignees:
#  - paalaas
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Bug description?
      description: If possible what was expected to happen?
      placeholder: Tell us what you see!
      value: "Bug description!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our model are you running?
      options:
        - 2
        - 3
        - 4
      default: 1
    validations:
      required: true
